Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network"
  config.vm.define "Devops"
  config.disksize.size = '50GB'
  config.vm.provider "virtualbox" do |v|
    v.memory = 4024
    v.cpus = 2
    v.name = "jenkins"
  end
end

